#!/usr/bin/env python3
"""{{ project_name }} — MCP stdio server (Bifrost-compatible NDJSON-RPC).

Server identity: {{ server_id }}
Authority: docs/engineering/CONSTITUTION.md §6
Generated by: templates/mcp-server-python (Copier {{ _copier_version }})
"""

from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from typing import Any

{% if use_postgres %}
import os

import psycopg
from psycopg.rows import dict_row

{% endif %}
SERVER_NAME = "{{ server_id }}"
SERVER_VERSION = "{{ initial_version }}"
PROTOCOL_VERSION = "2025-06-18"
SUPPORTED_VERSIONS = {"2024-11-05", "2025-03-26", "2025-06-18"}

{% if use_postgres %}
PG_HOST = "127.0.0.1"
PG_PORT = 55433
PG_DATABASE = "agent_core"
PG_USER = "postgres"
PG_PASSWORD = os.environ.get("AGENT_CORE_POSTGRES_PASSWORD", "")


def db() -> psycopg.Connection[Any]:
    return psycopg.connect(
        f"host={PG_HOST} port={PG_PORT} dbname={PG_DATABASE} user={PG_USER} password={PG_PASSWORD}",
        row_factory=dict_row,
    )
{% endif %}


def _now() -> str:
    return datetime.now(UTC).isoformat()


def _log(level: str, msg: str, **ctx: Any) -> None:
    sys.stderr.write(json.dumps({"ts": _now(), "level": level, "msg": msg, **ctx}) + "\n")
    sys.stderr.flush()


def _send(obj: Any) -> None:
    sys.stdout.write(json.dumps(obj) + "\n")
    sys.stdout.flush()


def _send_error(req_id: Any, code: int, message: str) -> None:
    _send({"jsonrpc": "2.0", "id": req_id, "error": {"code": code, "message": message}})


def _send_result(req_id: Any, result: Any) -> None:
    _send({"jsonrpc": "2.0", "id": req_id, "result": result})


def tool_defs() -> list[dict[str, Any]]:
    return [
        {
            "name": "{{ server_id | replace('-', '_') }}_status",
            "description": "Return server status.",
            "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
        },
    ]


def handle_tool_call(name: str, args: dict[str, Any]) -> Any:
    if name == "{{ server_id | replace('-', '_') }}_status":
        return {"ok": True, "server": SERVER_NAME, "version": SERVER_VERSION, "ts": _now()}
    raise ValueError(f"unknown tool: {name!r}")


def dispatch(msg: dict[str, Any]) -> None:
    method = msg.get("method", "")
    req_id = msg.get("id")
    params = msg.get("params", {})

    if method == "initialize":
        client_version = params.get("protocolVersion", PROTOCOL_VERSION)
        negotiated = client_version if client_version in SUPPORTED_VERSIONS else PROTOCOL_VERSION
        _send_result(req_id, {
            "protocolVersion": negotiated,
            "capabilities": {"tools": {}},
            "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
        })
    elif method in ("notifications/initialized", "initialized"):
        pass
    elif method == "tools/list":
        _send_result(req_id, {"tools": tool_defs()})
    elif method == "tools/call":
        tool_name = params.get("name", "")
        tool_args = params.get("arguments", {})
        _log("debug", "tool_call", tool=tool_name)
        try:
            result = handle_tool_call(tool_name, tool_args)
            _send_result(req_id, {
                "content": [{"type": "text", "text": json.dumps(result, default=str)}],
            })
        except Exception as exc:
            _log("error", "tool_call_error", tool=tool_name, error=type(exc).__name__)
            if req_id is not None:
                _send_error(req_id, -32000, f"{type(exc).__name__}: {exc}")
    elif method == "ping":
        if req_id is not None:
            _send_result(req_id, {})
    else:
        if req_id is not None:
            _send_error(req_id, -32601, f"method not found: {method!r}")


def main() -> None:
    _log("info", "startup", server=SERVER_NAME, version=SERVER_VERSION)
    for raw_line in sys.stdin:
        line = raw_line.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError as exc:
            _log("warn", "json_parse_error", error=str(exc))
            continue
        try:
            dispatch(msg)
        except Exception as exc:
            _log("error", "dispatch_error", error=type(exc).__name__, detail=str(exc))


if __name__ == "__main__":
    main()
