import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
import psycopg
from psycopg.rows import dict_row

def compute_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()

def write_atomic(target_path: Path, content: str):
    target_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = target_path.with_suffix(target_path.suffix + ".tmp")
    prev_path = target_path.with_suffix(target_path.suffix + ".previous")
    
    # Write temp file
    tmp_path.write_text(content, encoding="utf-8")
    
    # Backup existing file
    if target_path.exists():
        shutil.copy2(target_path, prev_path)
        
    # Replace target atomically
    shutil.move(tmp_path, target_path)

def generate_global_state(project_key: str = "agentcore-control-plane"):
    pw = os.environ.get("AGENT_CORE_POSTGRES_PASSWORD", "")
    dsn = f"host=127.0.0.1 port=55433 dbname=agent_core user=postgres password={pw}"
    
    conn = psycopg.connect(dsn, row_factory=dict_row)
    cur = conn.cursor()
    
    # Fetch active project info
    cur.execute("SELECT id, project_key, project_name, root_path, current_milestone FROM agentcore.projects WHERE project_key = %s;", (project_key,))
    project = cur.fetchone()
    if not project:
        cur.execute("SELECT id, project_key, project_name, root_path, current_milestone FROM agentcore.projects ORDER BY created_at DESC LIMIT 1;")
        project = cur.fetchone()
        
    project_id = str(project["id"]) if project else None
    p_key = project["project_key"] if project else project_key
    p_name = project["project_name"] if project else project_key
    p_milestone = project["current_milestone"] if project else "cursor-stage-b-integrity-harness"
    
    # Fetch source revision
    if project_id:
        cur.execute("""
            SELECT coalesce(max(occurred_at)::text, 'no-events') as sr
            FROM agentcore.evidence_events WHERE project_id = %s;
        """, (project_id,))
        source_rev = cur.fetchone()["sr"]
    else:
        source_rev = "no-events"
        
    generated_at = datetime.now(timezone.utc).isoformat()
    
    # Build GLOBAL_STATE content without hash first
    body_lines = [
        "<!-- Generated by AgentCore Projection Worker. PostgreSQL is canonical; do not hand-edit. -->",
        f"<!-- source_revision={source_rev} -->",
        "# GLOBAL_STATE — AgentCore Workstation State Projection",
        "",
        "## Active Project Snapshot",
        f"- Active Project: {p_name} ({p_key})",
        f"- Project ID: {project_id}",
        f"- Current Milestone: {p_milestone}",
        f"- Source Revision: {source_rev}",
        f"- Generated At: {generated_at}",
        "",
        "## 1. Operator-Verified Stable Working Preferences",
        "- Operator: Tony Valentine (ynotf)",
        "- Workstation Role: Primary AI Engineering Control Plane",
        "- Primary IDE / Agent Baseline: Single Bifrost gateway connection (`agentcore-gateway`)",
        "- Git Policy: Push after completed tasks; validate narrowly; secret/junk scan before commit; no unauthorized pull/fetch/merge/rebase/force-push.",
        "- Secret Policy: Windows User-scope environment variables only. No `.env` files anywhere.",
        "",
        "## 2. System-Verified Workstation Identity and Hardware",
        "- Host Identity: CHAOSCENTRAL",
        "- OS Version: Windows 11 Pro (10.0.26200 x64)",
        "- CPU: Intel Core i9-14900KF (24 cores / 32 threads)",
        "- RAM: 128 GB DDR5",
        "- GPU: NVIDIA GeForce RTX 4070 SUPER (12 GB VRAM)",
        "",
        "## 3. Drive Roles",
        "- C: OS, applications, user profile, live IDE configs (preserves OS; no heavy DB writes)",
        "- D: Source code repos, projects, worktrees, builds (`D:\\github\\agentcore-control-plane`)",
        "- E: Cold evidence, documentation archive, backups, WAL archive (NTFS / 64 KB)",
        "- F: AgentCore runtime, PostgreSQL 18, pgvector, hot indexes, and Bifrost (`F:\\AgentCore\\runtime`, `F:\\PostgreSQL18\\data`)",
        "- G: External backup target",
        "- H: Neutral Recall and Swarm-owned hot runtime/data only; no AgentCore runtime (`H:\\SwarmData`)",
        "- I: Disposable scratch, package cache, staging",
        "- J: Portable transfer media",
        "",
        "## 4. AgentCore Architecture Invariants",
        "- Canonical Authority: PostgreSQL 18 on port 55433 (`agent_core` DB)",
        "- Single Gateway: Non-Swarm IDEs connect ONLY to `agentcore-gateway` at `http://127.0.0.1:8080/mcp`",
        "- Memory Identity: `agentcore-memory` (stable ten-tool surface)",
        "- Unbounded Durable Memory: Model context window is bounded per-request; durable project history in PG is effectively unbounded.",
        "- Non-Destructive Compaction: Compaction summarizes context for model limits without deleting or altering original evidence.",
        "- Swarm Boundary: SwarmVault / SwarmClaw execution remains separate. Neutral shared SwarmRecall is available only through the server-side agentcore-memory projection; raw Recall tools and keys stay out of IDE baselines.",
        "",
        "## 5. Gateway and Database Endpoints",
        "- AgentCore Bifrost Gateway: `http://127.0.0.1:8080/mcp` (`agentcore-gateway`)",
        "- PostgreSQL 18 (Canonical AgentCore): `127.0.0.1:55433` (`agent_core`, `cognee_core`)",
        "- PostgreSQL 16 (Neutral shared semantic memory service-owned backend): `127.0.0.1:65432` (`swarmrecall`); AgentCore has no direct SQL route.",
        "- PostgreSQL 16 legacy quarantine: `127.0.0.1:55432` is offline/preserved evidence, never an active memory route.",
        "- Meilisearch: `http://127.0.0.1:7700`",
        "- Neutral SwarmRecall API: `http://127.0.0.1:3300` (server-side adapters only; never direct IDE access)",
        "",
        "## 6. Global Security Boundaries",
        "- No `.env` files or hardcoded secret material.",
        "- No direct database access or credentials for normal IDE agents.",
        "- Path Isolation: Agents write only within assigned project/worktree paths and role-appropriate runtime roots.",
        "- Zero Swarm Exposure: Non-Swarm IDEs do not expose Swarm MCP, Swarm DBs, or Swarm files.",
        "- Operator Gates: DB schema migrations, live DDL, live IDE config mutations, service mutations, and force-pushes require explicit operator approval.",
        ""
    ]
    
    body_text = "\n".join(body_lines)
    content_hash = compute_sha256(body_text)
    full_content = body_text + f"\nContent SHA-256: {content_hash}\n"
    
    target_path = Path(r"C:\Users\ynotf\.agentcore\GLOBAL_STATE.md")
    write_atomic(target_path, full_content)
    
    # Record revision in DB
    cur.execute("""
        SELECT agentcore.record_projection_revision(
            %s, 'global_state', %s, %s, %s
        ) as rev;
    """, (None, str(target_path), content_hash, source_rev))
    new_rev = cur.fetchone()["rev"]
    conn.commit()
    
    cur.close()
    conn.close()
    
    print(f"Generated GLOBAL_STATE.md at {target_path}")
    print(f"New Revision: {new_rev}")
    print(f"Content SHA-256: {content_hash}")
    return new_rev, content_hash

if __name__ == "__main__":
    generate_global_state()
