"""Render per-IDE GLOBAL_RULES.md files from the canonical global agent policy.

Source of truth:
  contracts/global-agent-policy.yaml   (semantic rules)
  ide-profiles/<ide>/IDE_PROFILE.yaml  (per-IDE facts, editability, limitations)

Output (all derived; do not hand-edit):
  ide-profiles/<ide>/GLOBAL_RULES.md
  ide-profiles/<ide>/INSTALL_OR_UPDATE.md
  ide-profiles/<ide>/VALIDATION.md

Usage:
  python scripts/render_ide_rules.py            # write files
  python scripts/render_ide_rules.py --check    # exit 1 if any rendered file is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
POLICY_PATH = REPO / "contracts" / "global-agent-policy.yaml"
PROFILES_ROOT = REPO / "ide-profiles"

HEADER_KEYS = [
    ("IDE profile ID", lambda p: p["ide_id"]),
    ("Canonical policy source", lambda p: "contracts/global-agent-policy.yaml"),
    ("IDE overlay source", lambda p: f"ide-profiles/{p['ide_id']}/IDE_PROFILE.yaml"),
    ("Model context profiles", lambda p: "contracts/model-context-profiles.json (model-aware; no durable-memory cap)"),
    ("Live global-rule target", lambda p: str(p.get("live_global_rule_target", "unverified"))),
    ("Live MCP config target", lambda p: str(p.get("live_mcp_config_target", "unverified"))),
    ("Cursor may edit global rules", lambda p: _editability_answer(p, "global_rules")),
    ("Cursor may edit MCP config", lambda p: _editability_answer(p, "mcp_config")),
    ("Installation mode", lambda p: str(p.get("installation_mode", "unverified"))),
    ("Backup required", lambda p: _yn(p.get("backup_required"))),
    ("Validation required", lambda p: _yn(p.get("validation_required"))),
    ("Restart required", lambda p: _yn(p.get("restart_required"))),
    ("Last validated", lambda p: str(p.get("last_validation_date", "never"))),
]


def _yn(value) -> str:
    if value is True:
        return "yes"
    if value is False:
        return "no"
    return "unverified"


def _editability_answer(profile: dict, key: str) -> str:
    mode = (profile.get("editability") or {}).get(key, "unverified")
    if mode == "direct_write":
        return "yes (direct_write; live edits remain approval-gated by policy)"
    if mode in ("generated_prompt", "manual_import"):
        return f"no ({mode})"
    if mode == "unsupported":
        return "no (unsupported by product)"
    return "unverified"


def render(profile: dict, policy: dict) -> str:
    lines: list[str] = []
    lines.append(f"# Global Agent Rules — {profile.get('display_name', profile['ide_id'])}")
    lines.append("")
    lines.append(
        "> **DERIVED FILE — do not hand-edit.** Generated by `scripts/render_ide_rules.py` from "
        f"`contracts/global-agent-policy.yaml` (policy_revision {policy['policy_revision']}). "
        "Semantic changes go into the canonical policy, never into this rendering."
    )
    lines.append("")
    lines.append("## Profile header")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("| -- | -- |")
    for label, getter in HEADER_KEYS:
        lines.append(f"| {label} | {getter(profile)} |")
    lines.append("")
    lines.append("## Mandatory rules")
    lines.append("")
    for index, rule in enumerate(policy["mandatory_rules"], start=1):
        text = " ".join(str(rule["rule"]).split())
        lines.append(f"{index}. **{rule['title']}.** {text}")
    lines.append("")
    lines.append("## Forbidden routes")
    lines.append("")
    for route in policy["forbidden_routes"]:
        lines.append(f"- {route}")
    lines.append("")
    limitations = profile.get("known_limitations") or []
    gaps = profile.get("semantic_parity_gaps") or []
    lines.append("## Product-specific notes and omissions")
    lines.append("")
    if not limitations and not gaps:
        lines.append("- None recorded. Full semantic parity with the canonical policy.")
    for item in limitations:
        lines.append(f"- Limitation: {item}")
    for item in gaps:
        lines.append(f"- Parity gap: {item}")
    lines.append("")
    return "\n".join(lines)


def render_install(profile: dict, policy: dict) -> str:
    ide = profile["ide_id"]
    mode = str(profile.get("installation_mode", "unverified"))
    mcp_template = "MCP_CONFIG_TEMPLATE.toml" if ide == "codex" else "MCP_CONFIG_TEMPLATE.json"
    lines = [
        f"# Install / Update — {profile.get('display_name', ide)}",
        "",
        "> **DERIVED FILE — do not hand-edit.** Generated by `scripts/render_ide_rules.py`.",
        "",
        f"Installation mode: **{mode}**. Live IDE files are never edited without explicit operator",
        "authorization, a timestamped backup, and post-change validation.",
        "",
        "## Rules delivery",
        "",
        f"1. Canonical semantics: `contracts/global-agent-policy.yaml` → rendered `ide-profiles/{ide}/GLOBAL_RULES.md`.",
        f"2. Delivery mechanism for this IDE: {_editability_answer(profile, 'global_rules')} — target: {profile.get('live_global_rule_target', 'unverified')}.",
        "3. If delivery is `manual_import`/`generated_prompt`, hand the rendered GLOBAL_RULES.md content to the operator or paste it via the documented UI path. Do not skip rules silently.",
        "",
        "## MCP configuration",
        "",
        f"1. Template: `ide-profiles/{ide}/{mcp_template}` (derived from `renderers/gateway-clients/{ide}.json`).",
        f"2. Live target: `{profile.get('live_mcp_config_target', 'unverified')}` — exactly one `agentcore-gateway` entry.",
        "3. Follow `docs/prompts/install-agentcore-gateway-in-ide.md` for the approved live-change procedure (backup first).",
        f"4. Env handling: {profile.get('env_var_handling', 'unverified')}.",
        f"5. Restart behavior: {profile.get('restart_behavior', 'unverified')}.",
        "",
        "## After any change",
        "",
        f"Run the checks in `ide-profiles/{ide}/VALIDATION.md` and record the date in `IDE_PROFILE.yaml` (`last_validation_date`).",
        "",
    ]
    return "\n".join(lines)


def render_validation(profile: dict, policy: dict) -> str:
    ide = profile["ide_id"]
    lines = [
        f"# Validation — {profile.get('display_name', ide)}",
        "",
        "> **DERIVED FILE — do not hand-edit.** Generated by `scripts/render_ide_rules.py`.",
        "",
        "Run after installing or updating rules/MCP config for this IDE:",
        "",
        "1. The live MCP config contains exactly one `agentcore-gateway` entry (URL `http://127.0.0.1:8080/mcp`) and no direct per-tool or Swarm entries.",
        "2. No resolved secret values appear anywhere in Git-tracked files (env references only; materialized VK allowed in the live config only where the profile documents no env-header support).",
        "3. The IDE lists gateway tools after restart (tools/list through `agentcore-gateway` succeeds).",
        "4. `agentcore-memory` responds through `memory_status`, with degraded component state clearly reported.",
        "5. The delivered rules match `ide-profiles/" + ide + "/GLOBAL_RULES.md` (semantic parity; record any product-specific omission in `IDE_PROFILE.yaml`).",
        "6. Session self-enrollment records the verified client, repository/worktree/Git identity, selected provider/model, and named model context profile; it does not lower the IDE model's configured hard context window.",
        "7. `startup_context` reports a model-aware profile, and `retrieve_context` recovery mode returns bounded chronology with source IDs, hashes, exact expansion references, omitted counts, and a continuation cursor when more history exists.",
        "8. Repo validators pass: `python scripts/bifrost/validate_contracts.py`, `python scripts/bifrost/test_contracts.py`, and `python -m pytest scripts/agentcore_memory/test_recovery.py -q`.",
        "",
        f"Record results and date in `IDE_PROFILE.yaml` (`last_validation_date`). Current recorded validation: {profile.get('last_validation_date', 'never')}.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify rendered files are current")
    args = parser.parse_args()

    policy = yaml.safe_load(POLICY_PATH.read_text(encoding="utf-8"))
    stale: list[str] = []
    rendered_count = 0

    for profile_path in sorted(PROFILES_ROOT.glob("*/IDE_PROFILE.yaml")):
        profile = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
        if profile.get("swarm_managed"):
            continue
        outputs = {
            profile_path.parent / "GLOBAL_RULES.md": render(profile, policy),
            profile_path.parent / "INSTALL_OR_UPDATE.md": render_install(profile, policy),
            profile_path.parent / "VALIDATION.md": render_validation(profile, policy),
        }
        for output_path, content in outputs.items():
            if args.check:
                existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
                if existing != content:
                    stale.append(str(output_path.relative_to(REPO)))
            else:
                output_path.write_text(content, encoding="utf-8", newline="\n")
                rendered_count += 1
                print(f"rendered {output_path.relative_to(REPO)}")

    if args.check:
        if stale:
            print("STALE renderings (run scripts/render_ide_rules.py):")
            for path in stale:
                print(f"  {path}")
            return 1
        print("OK: all IDE GLOBAL_RULES.md renderings current")
        return 0

    print(f"OK: rendered {rendered_count} IDE rule files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
