<!-- Generated by Invoke-M3ProjectionWorker.ps1. PostgreSQL is canonical; do not hand-edit. -->
<!-- project_key=m3_project_20260716015407 project_id=23b08121-4dd8-49b3-992a-1a30c9aaf917 source_revision=2026-07-16 01:54:18.161828-04 -->
# CONTEXT INDEX â€” M3 Lossless Context Test Project

## Summary Index

- L1 [active_dynamic] M3 L1 event span ├óΓé¼ΓÇ¥ 67cc5cab57c7 tokens=80
- L2 [static_stable] M3 L2 session summary ├óΓé¼ΓÇ¥ 79fb9256eaf6 tokens=70
- L3 [static_stable] M3 L3 project chronology ├óΓé¼ΓÇ¥ d8964ac2ab7b tokens=60

Content SHA-256: b537e6c9a9308564f9bd6800380940f88e35802e096989861e1b94c104c58311
