<!-- Generated by Invoke-M3ProjectionWorker.ps1. PostgreSQL is canonical; do not hand-edit. -->
<!-- project_key=m3_project_20260716003314 project_id=2da7f36d-124e-47e0-94ff-76f8543ede31 source_revision=2026-07-16 00:33:31.484555-04 -->
# CONTEXT INDEX â€” M3 Lossless Context Test Project

## Summary Index

- L1 [active_dynamic] M3 L1 event span ├óΓé¼ΓÇ¥ a560c8981a16 tokens=80
- L2 [static_stable] M3 L2 session summary ├óΓé¼ΓÇ¥ 31e3f829b982 tokens=70
- L3 [static_stable] M3 L3 project chronology ├óΓé¼ΓÇ¥ d8104adfd817 tokens=60

Content SHA-256: $contextHash
