<!-- Generated by Invoke-M3ProjectionWorker.ps1. PostgreSQL is canonical; do not hand-edit. -->
<!-- project_key=m3_project_20260715210053 project_id=3f4173da-7876-4381-adeb-933feb3b6d9f source_revision=2026-07-15 21:01:06.193547-04 -->
# DECISIONS â€” M3 Lossless Context Test Project

- No decisions recorded.

Content SHA-256: $decisionsHash
