<!-- Generated by Invoke-M3ProjectionWorker.ps1. PostgreSQL is canonical; do not hand-edit. -->
<!-- project_key=agentcore-control-plane project_id=8a3bbea1-cf45-4520-9cbb-c0324baa1ac1 source_revision=2026-07-23 23:08:06.684173-04 -->
# DECISIONS â€” AgentCore Control Plane

- {"note": "This decision belongs to Project A only", "project": "agentcore-control-plane", "secret_marker": "PROJECT_A_PROTECTED_DATA"}
- {"commit": "794d972", "summary": "Docs reconciled to BLUEPRINT as canonical truth; stale degraded-memory and pre-M6 lease claims removed; OpenRouter dormant vs authenticated_dormant vocabulary fixed; cross-links added across authority and ops docs.", "key_paths": ["BLUEPRINT.md", "DOC_AUTHORITY.md", "CONTEXT_BLOCK.md", "docs/operations/OPENROUTER_MCP.md", "docs/bifrost/UNIFIED_GATEWAY_SETUP.md"], "validation": "validate_contracts.py OK", "left_uncommitted": ["workflow_cli.py", "server.py", "deepagents_worker.py", "studio-interrupt artifacts"]}

Content SHA-256: 01e8b3a2c838bee39c6d3b237847f6c132567da6227286a5ad8ca3541265bd59
