<!-- Generated by Invoke-M3ProjectionWorker.ps1. PostgreSQL is canonical; do not hand-edit. -->
<!-- project_key=m3_project_20260716015407 project_id=23b08121-4dd8-49b3-992a-1a30c9aaf917 source_revision=2026-07-16 01:54:18.161828-04 -->
# DECISIONS â€” M3 Lossless Context Test Project

- No decisions recorded.

Content SHA-256: 9b9446cae4a41b553f48322fe68eb3b99e455b52dfc9179bfa00accb76cf5733
