<!-- Generated by Invoke-M3ProjectionWorker.ps1. PostgreSQL is canonical; do not hand-edit. -->
<!-- project_key=m3_project_20260715210053 project_id=3f4173da-7876-4381-adeb-933feb3b6d9f source_revision=2026-07-15 21:01:06.193547-04 -->
# STATE â€” M3 Lossless Context Test Project

Project key: $ProjectKey
Current Milestone: $(@{root_path=D:\github\agentcore-control-plane; created_at=2026-07-15T21:00:54.870209-04:00; project_id=3f4173da-7876-4381-adeb-933feb3b6d9f; project_key=m3_project_20260715210053; project_name=M3 Lossless Context Test Project; current_milestone=M3}.current_milestone)
Source revision: $sourceRevision

## Current Truth

- PostgreSQL is canonical.
- Agents contribute through gentcore-memory; STATE files are generated projections.
- Active context and stable/static context are separated by context_bucket.

## Counts

- L0 raw accepted events: 4
- L1 event-span summaries: 1
- L2 session summaries: 1
- L3 project chronology summaries: 1
- Open fact proposals: 1

## Recent Chronology

- 2026-07-16 01:00:54Z prompt fd2d17cd
- 2026-07-16 01:00:54Z prompt c4ce22a5
- 2026-07-16 01:00:54Z message 6d3495c9
- 2026-07-16 01:00:55Z accepted_evidence b2bc2f6f

Content SHA-256: $projectStateHash
